### ISSUE TITLE
get_headers causes php error

### ISSUE THREAD

**Issue by PHOENIX-MEDIA** [integer-net/BillSAFE#3]
We found this error in the system.log:

ERR (3): Warning: get_headers(): This function may only be used against URLs  in /data/vhosts/test.bausep.de/htdocs/app/code/community/Netresearch/Billsafe/Model/Client/Base.php on line 20

And this in exception.log:

ERR (3): 
exception 'Mage_Core_Exception' with message 'BillSAFE server is temporarily not available, please try again later' in /htdocs/app/Mage.php:595
Stack trace:
#0 /htdocs/app/code/community/Netresearch/Billsafe/Model/Client/Base.php(30): Mage::throwException('BillSAFE server...')
#1 /htdocs/app/code/community/Netresearch/Billsafe/Model/Client.php(377): Netresearch_Billsafe_Model_Client_Base->__call('getAgreedHandli...', Array)
#2 /htdocs/app/code/community/Netresearch/Billsafe/Model/Client.php(377): Netresearch_Billsafe_Model_Client_Base->getAgreedHandlingCharges(Array)
#3 /htdocs/app/code/community/Netresearch/Billsafe/Model/Client.php(395): Netresearch_Billsafe_Model_Client->getAgreedHandlingCharges('charge')
#4 /htdocs/app/code/community/Netresearch/Billsafe/Model/Config.php(483): Netresearch_Billsafe_Model_Client->getMaxFee()
#5 /htdocs/app/code/community/Netresearch/Billsafe/Model/Config/Maxfee.php(77): Netresearch_Billsafe_Model_Config->getMaxFee()
#6 /htdocs/app/code/community/Netresearch/Billsafe/Model/Config/Maxfee.php(22): Netresearch_Billsafe_Model_Config_Maxfee->getMaxFee()
#7 /htdocs/app/code/core/Mage/Core/Model/Config/Data.php(78): Netresearch_Billsafe_Model_Config_Maxfee->_afterLoad()
#8 /htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(334): Mage_Core_Model_Config_Data->afterLoad()
#9 /htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#10 /htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#11 /htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#12 /htdocs/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#13 /htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#14 /htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#15 /htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#17 /htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /htdocs/index.php(83): Mage::run('', 'store')
#19 {main}

I guess this WSDL check need to be implemented in a different way (like downloading it via cURL).

**Comment by avstudnitz** [comment]
This is no official repository of the billsafe module, just a mirror. We won't do changes here, please contact the module developers.
